using System.Globalization;

namespace TrueCompare.Services;

public sealed class AppText
{
    private static readonly IReadOnlyDictionary<string, string> Pt = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["Layout.Credits"] = "Créditos",
        ["Layout.Logout"] = "Logout",
        ["Layout.User"] = "Utilizador",
        ["Layout.Login"] = "Login",
        ["Layout.CreateAccount"] = "Criar conta",
        ["Layout.Rights"] = "2025©All rights reserved.",
        ["Layout.Version"] = "◇ TrueCompare V1",
        ["Nav.Tagline"] = "AI Verified Products",
        ["Nav.Open"] = "Abrir navegação",
        ["Nav.NewChat"] = "Novo Chat",
        ["Nav.Categories"] = "Categorias",
        ["Nav.History"] = "Histórico",
        ["Nav.Activity"] = "Atividade",
        ["Nav.Settings"] = "Definições",

        ["Home.Title"] = "O que queres comparar hoje?",
        ["Home.Lead"] = "3 pesquisas grátis · vendedores verificados · alertas de preço",
        ["Home.ProductAria"] = "Produto a comparar",
        ["Home.CompareAria"] = "Comparar",
        ["Home.Capabilities"] = "Capacidades principais",
        ["Home.Compare"] = "Comparar",
        ["Home.Products"] = "Produtos",
        ["Home.Verify"] = "Verificar",
        ["Home.Authenticity"] = "Autenticidade",
        ["Home.Weigh"] = "Ponderar",
        ["Home.Criteria"] = "Critérios",
        ["Home.Choose"] = "Escolher",
        ["Home.Seller"] = "Vendedor",
        ["Home.Buy"] = "Comprar",
        ["Home.Now"] = "Agora",
        ["Home.Master"] = "Dominar",
        ["Home.Flows"] = "Fluxos",
        ["Home.DefaultPrompt"] = "portátil profissional 14\", até 1500€, autonomia >10h, leve",
        ["Home.DefaultCategory"] = "Eletrodomésticos eficiência A+++",
        ["Home.CategoryPrompt"] = "{0}: melhor preço, vendedores verificados, baixo risco.",
        ["Home.MissingProduct"] = "Produto em falta.",
        ["Home.NoCredits"] = "Sem créditos disponíveis.",

        ["Criteria.PageTitle"] = "Critérios - TrueCompare",
        ["Criteria.Title"] = "Define o que valorizas",
        ["Criteria.Lead"] = "Preço, qualidade, risco e garantia no peso certo.",
        ["Criteria.ModeAria"] = "Modo de análise",
        ["Criteria.TabAi"] = "IA",
        ["Criteria.TabPrice"] = "PREÇO",
        ["Criteria.TabWarranty"] = "GARANTIA",
        ["Criteria.TabDelivery"] = "ENTREGA",
        ["Criteria.TabRisk"] = "RISCO",
        ["Criteria.LookingFor"] = "Procuro:",
        ["Criteria.CompareProducts"] = "Comparar produtos →",
        ["Criteria.RankingTitle"] = "Ranking final",
        ["Criteria.RankingLead"] = "Sem patrocínios. Sem afiliados. Sem ruído.",
        ["Criteria.Signals"] = "Sinais usados",
        ["Criteria.OfficialSpecs"] = "Specs oficiais",
        ["Criteria.VerifiedSellers"] = "Vendedores verificados",
        ["Criteria.TotalPrice"] = "Preço total",
        ["Criteria.FraudRisk"] = "Risco anti-fraude",
        ["Criteria.Confidence"] = "Confiança do ranking",
        ["Criteria.DefaultQuery"] = "portátil profissional 14\", até 1500€, autonomia >10h, leve",

        ["Results.PageTitle"] = "Resultados - TrueCompare",
        ["Results.Title"] = "Resultados comparativos",
        ["Results.Subtitle"] = "{0} produtos · preço, garantia, risco e performance ponderados.",
        ["Results.AddProduct"] = "+ Adicionar produto",
        ["Results.AiSuggestion"] = "Sugestão IA",
        ["Results.Analyzing"] = "A analisar",
        ["Results.Preparing"] = "A preparar recomendações...",
        ["Results.Spec"] = "Spec",
        ["Results.Verified"] = "✓ Verificado · sem patrocínio",
        ["Results.Details"] = "Ver detalhes",
        ["Results.Disclaimer"] = "Os resultados não são influenciados por marcas, retalhistas ou parceiros comerciais.",
        ["Results.DefaultQuery"] = "produto com melhor preço, garantia e baixo risco",

        ["Product.PageTitle"] = "Detalhe - TrueCompare",
        ["Product.NotFound"] = "Produto não encontrado",
        ["Product.Results"] = "Ver resultados",
        ["Product.Title"] = "Produto verificado",
        ["Product.Conditions"] = "Ver condições",
        ["Product.Score"] = "Score IA",
        ["Product.Verified"] = "✓ Verificado pela TrueCompare",
        ["Product.VerifiedLead"] = "Fornecedor, stock, garantia e risco validados",
        ["Product.AiAnalysis"] = "Análise IA",
        ["Product.FraudAlerts"] = "! Alertas anti-fraude",
        ["Product.Clean"] = "Limpo",

        ["Checkout.PageTitle"] = "Compra - TrueCompare",
        ["Checkout.Title"] = "Comprar pelo melhor preço",
        ["Checkout.Lead"] = "Escolhe o vendedor ou define o preço alvo.",
        ["Checkout.Seller"] = "Vendedor",
        ["Checkout.Price"] = "Preço",
        ["Checkout.Delivery"] = "Entrega",
        ["Checkout.Warranty"] = "Garantia",
        ["Checkout.Status"] = "Status",
        ["Checkout.BestPrice"] = "Melhor preço",
        ["Checkout.RecommendedSeller"] = "Vendedor recomendado",
        ["Checkout.BestPriceVerified"] = "✓ Melhor preço verificado pela TrueCompare",
        ["Checkout.SelectedOfferLine"] = "{0} · entrega {1}",
        ["Checkout.Subtotal"] = "Subtotal",
        ["Checkout.Shipping"] = "Envio",
        ["Checkout.ConfirmWithSeller"] = "Confirmar no vendedor",
        ["Checkout.RecommendedPrice"] = "Preço recomendado",
        ["Checkout.OrderNow"] = "Encomendar agora",
        ["Checkout.PriceAlert"] = "Alerta de preço",
        ["Checkout.TargetPrice"] = "Preço alvo",
        ["Checkout.NotifyMe"] = "Avisar-me",

        ["Features.PageTitle"] = "Funcionalidades - TrueCompare",
        ["Features.Title"] = "Funcionalidades",
        ["Features.Lead"] = "Comparar, verificar, comprar e acompanhar preços.",
        ["Tutorials.PageTitle"] = "Tutoriais - TrueCompare",
        ["Tutorials.Title"] = "Centro de tutoriais",
        ["Tutorials.Lead"] = "Fluxos curtos para compra, verificação e alertas.",
        ["Tutorials.FilterAria"] = "Filtro de tutoriais",
        ["Tutorials.All"] = "Todos",
        ["Tutorials.Beginners"] = "Iniciantes",
        ["Tutorials.Advanced"] = "Avançado",
        ["Tutorials.Security"] = "Segurança",
        ["Tutorials.Orders"] = "Encomendas",

        ["Auth.LoginPageTitle"] = "Login - TrueCompare",
        ["Auth.LoginEyebrow"] = "Acesso TrueCompare",
        ["Auth.LoginTitle"] = "Entrar",
        ["Auth.LoginWithGoogle"] = "Entrar com Gmail",
        ["Auth.Or"] = "ou",
        ["Auth.Password"] = "Password",
        ["Auth.RememberMe"] = "Manter sessão iniciada",
        ["Auth.LoginButton"] = "Entrar",
        ["Auth.NoAccount"] = "Ainda não tens conta?",
        ["Auth.CreateAccount"] = "Criar conta",
        ["Auth.RegisterPageTitle"] = "Criar conta - TrueCompare",
        ["Auth.FreeSearches"] = "3 pesquisas gratuitas",
        ["Auth.RegisterTitle"] = "Criar conta",
        ["Auth.CreateWithGoogle"] = "Criar com Gmail",
        ["Auth.ConfirmPassword"] = "Confirmar password",
        ["Auth.AlreadyHaveAccount"] = "Já tens conta?",

        ["Credits.PageTitle"] = "Créditos - TrueCompare",
        ["Credits.Eyebrow"] = "Créditos TrueCompare",
        ["Credits.Title"] = "Créditos",
        ["Credits.NewSearch"] = "Nova pesquisa",
        ["Credits.Loading"] = "A carregar créditos...",
        ["Credits.FreeUsed"] = "Pesquisas gratuitas usadas",
        ["Credits.FreeRemaining"] = "Gratuitas restantes",
        ["Credits.Available"] = "Créditos disponíveis",
        ["Credits.PayByCard"] = "Pagar com cartão",
        ["Credits.PackageCredits"] = "{0} créditos",
        ["Credits.SuccessPageTitle"] = "Pagamento recebido - TrueCompare",
        ["Credits.SuccessEyebrow"] = "Stripe",
        ["Credits.SuccessTitle"] = "Créditos adicionados",
        ["Credits.SuccessLead"] = "Pagamento confirmado. Os teus créditos estão disponíveis.",
        ["Credits.ViewCredits"] = "Ver créditos",

        ["Error.Title"] = "Erro",
        ["Error.Message"] = "Algo correu mal.",
        ["Error.Back"] = "Voltar",
        ["Blazor.Error"] = "Ocorreu um erro inesperado.",
        ["Blazor.Reload"] = "Recarregar"
    };

    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["Layout.Credits"] = "Credits",
        ["Layout.Logout"] = "Logout",
        ["Layout.User"] = "User",
        ["Layout.Login"] = "Login",
        ["Layout.CreateAccount"] = "Create account",
        ["Layout.Rights"] = "2025©All rights reserved.",
        ["Layout.Version"] = "◇ TrueCompare V1",
        ["Nav.Tagline"] = "AI Verified Products",
        ["Nav.Open"] = "Open navigation",
        ["Nav.NewChat"] = "New Chat",
        ["Nav.Categories"] = "Categories",
        ["Nav.History"] = "History",
        ["Nav.Activity"] = "Activity",
        ["Nav.Settings"] = "Settings",

        ["Home.Title"] = "What do you want to compare today?",
        ["Home.Lead"] = "3 free searches · verified sellers · price alerts",
        ["Home.ProductAria"] = "Product to compare",
        ["Home.CompareAria"] = "Compare",
        ["Home.Capabilities"] = "Main capabilities",
        ["Home.Compare"] = "Compare",
        ["Home.Products"] = "Products",
        ["Home.Verify"] = "Verify",
        ["Home.Authenticity"] = "Authenticity",
        ["Home.Weigh"] = "Weigh",
        ["Home.Criteria"] = "Criteria",
        ["Home.Choose"] = "Choose",
        ["Home.Seller"] = "Seller",
        ["Home.Buy"] = "Buy",
        ["Home.Now"] = "Now",
        ["Home.Master"] = "Master",
        ["Home.Flows"] = "Flows",
        ["Home.DefaultPrompt"] = "professional 14\" laptop, up to 1500€, battery >10h, light",
        ["Home.DefaultCategory"] = "A+++ efficient appliances",
        ["Home.CategoryPrompt"] = "{0}: best price, verified sellers, low risk.",
        ["Home.MissingProduct"] = "Product missing.",
        ["Home.NoCredits"] = "No credits available.",

        ["Criteria.PageTitle"] = "Criteria - TrueCompare",
        ["Criteria.Title"] = "Define what matters",
        ["Criteria.Lead"] = "Price, quality, risk and warranty with the right weight.",
        ["Criteria.ModeAria"] = "Analysis mode",
        ["Criteria.TabAi"] = "AI",
        ["Criteria.TabPrice"] = "PRICE",
        ["Criteria.TabWarranty"] = "WARRANTY",
        ["Criteria.TabDelivery"] = "DELIVERY",
        ["Criteria.TabRisk"] = "RISK",
        ["Criteria.LookingFor"] = "Looking for:",
        ["Criteria.CompareProducts"] = "Compare products →",
        ["Criteria.RankingTitle"] = "Final ranking",
        ["Criteria.RankingLead"] = "No sponsorships. No affiliates. No noise.",
        ["Criteria.Signals"] = "Signals used",
        ["Criteria.OfficialSpecs"] = "Official specs",
        ["Criteria.VerifiedSellers"] = "Verified sellers",
        ["Criteria.TotalPrice"] = "Total price",
        ["Criteria.FraudRisk"] = "Anti-fraud risk",
        ["Criteria.Confidence"] = "Ranking confidence",
        ["Criteria.DefaultQuery"] = "professional 14\" laptop, up to 1500€, battery >10h, light",

        ["Results.PageTitle"] = "Results - TrueCompare",
        ["Results.Title"] = "Comparison results",
        ["Results.Subtitle"] = "{0} products · price, warranty, risk and performance weighted.",
        ["Results.AddProduct"] = "+ Add product",
        ["Results.AiSuggestion"] = "AI suggestion",
        ["Results.Analyzing"] = "Analyzing",
        ["Results.Preparing"] = "Preparing recommendations...",
        ["Results.Spec"] = "Spec",
        ["Results.Verified"] = "✓ Verified · no sponsorship",
        ["Results.Details"] = "View details",
        ["Results.Disclaimer"] = "Results are not influenced by brands, retailers or commercial partners.",
        ["Results.DefaultQuery"] = "product with best price, warranty and low risk",

        ["Product.PageTitle"] = "Details - TrueCompare",
        ["Product.NotFound"] = "Product not found",
        ["Product.Results"] = "View results",
        ["Product.Title"] = "Verified product",
        ["Product.Conditions"] = "View conditions",
        ["Product.Score"] = "AI score",
        ["Product.Verified"] = "✓ Verified by TrueCompare",
        ["Product.VerifiedLead"] = "Supplier, stock, warranty and risk validated",
        ["Product.AiAnalysis"] = "AI analysis",
        ["Product.FraudAlerts"] = "! Anti-fraud alerts",
        ["Product.Clean"] = "Clean",

        ["Checkout.PageTitle"] = "Purchase - TrueCompare",
        ["Checkout.Title"] = "Buy at the best price",
        ["Checkout.Lead"] = "Choose the seller or set a target price.",
        ["Checkout.Seller"] = "Seller",
        ["Checkout.Price"] = "Price",
        ["Checkout.Delivery"] = "Delivery",
        ["Checkout.Warranty"] = "Warranty",
        ["Checkout.Status"] = "Status",
        ["Checkout.BestPrice"] = "Best price",
        ["Checkout.RecommendedSeller"] = "Recommended seller",
        ["Checkout.BestPriceVerified"] = "✓ Best price verified by TrueCompare",
        ["Checkout.SelectedOfferLine"] = "{0} · delivery {1}",
        ["Checkout.Subtotal"] = "Subtotal",
        ["Checkout.Shipping"] = "Shipping",
        ["Checkout.ConfirmWithSeller"] = "Confirm with seller",
        ["Checkout.RecommendedPrice"] = "Recommended price",
        ["Checkout.OrderNow"] = "Order now",
        ["Checkout.PriceAlert"] = "Price alert",
        ["Checkout.TargetPrice"] = "Target price",
        ["Checkout.NotifyMe"] = "Notify me",

        ["Features.PageTitle"] = "Features - TrueCompare",
        ["Features.Title"] = "Features",
        ["Features.Lead"] = "Compare, verify, buy and track prices.",
        ["Tutorials.PageTitle"] = "Tutorials - TrueCompare",
        ["Tutorials.Title"] = "Tutorial center",
        ["Tutorials.Lead"] = "Short flows for purchase, verification and alerts.",
        ["Tutorials.FilterAria"] = "Tutorial filter",
        ["Tutorials.All"] = "All",
        ["Tutorials.Beginners"] = "Beginners",
        ["Tutorials.Advanced"] = "Advanced",
        ["Tutorials.Security"] = "Security",
        ["Tutorials.Orders"] = "Orders",

        ["Auth.LoginPageTitle"] = "Login - TrueCompare",
        ["Auth.LoginEyebrow"] = "TrueCompare access",
        ["Auth.LoginTitle"] = "Sign in",
        ["Auth.LoginWithGoogle"] = "Sign in with Gmail",
        ["Auth.Or"] = "or",
        ["Auth.Password"] = "Password",
        ["Auth.RememberMe"] = "Keep me signed in",
        ["Auth.LoginButton"] = "Sign in",
        ["Auth.NoAccount"] = "No account yet?",
        ["Auth.CreateAccount"] = "Create account",
        ["Auth.RegisterPageTitle"] = "Create account - TrueCompare",
        ["Auth.FreeSearches"] = "3 free searches",
        ["Auth.RegisterTitle"] = "Create account",
        ["Auth.CreateWithGoogle"] = "Create with Gmail",
        ["Auth.ConfirmPassword"] = "Confirm password",
        ["Auth.AlreadyHaveAccount"] = "Already have an account?",

        ["Credits.PageTitle"] = "Credits - TrueCompare",
        ["Credits.Eyebrow"] = "TrueCompare credits",
        ["Credits.Title"] = "Credits",
        ["Credits.NewSearch"] = "New search",
        ["Credits.Loading"] = "Loading credits...",
        ["Credits.FreeUsed"] = "Free searches used",
        ["Credits.FreeRemaining"] = "Free remaining",
        ["Credits.Available"] = "Available credits",
        ["Credits.PayByCard"] = "Pay by card",
        ["Credits.PackageCredits"] = "{0} credits",
        ["Credits.SuccessPageTitle"] = "Payment received - TrueCompare",
        ["Credits.SuccessEyebrow"] = "Stripe",
        ["Credits.SuccessTitle"] = "Credits added",
        ["Credits.SuccessLead"] = "Payment confirmed. Your credits are available.",
        ["Credits.ViewCredits"] = "View credits",

        ["Error.Title"] = "Error",
        ["Error.Message"] = "Something went wrong.",
        ["Error.Back"] = "Back",
        ["Blazor.Error"] = "An unhandled error has occurred.",
        ["Blazor.Reload"] = "Reload"
    };

    public string this[string key] => Translate(key);

    public bool IsEnglish => CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("en", StringComparison.OrdinalIgnoreCase);

    public string Format(string key, params object[] args)
    {
        return string.Format(CultureInfo.CurrentUICulture, Translate(key), args);
    }

    public string Translate(string key)
    {
        if (IsEnglish && En.TryGetValue(key, out var enValue))
        {
            return enValue;
        }

        return Pt.TryGetValue(key, out var ptValue) ? ptValue : key;
    }

    public string Pick(string pt, string en)
    {
        return IsEnglish ? en : pt;
    }
}
